/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppCoachRouteImport } from './routes/_app/coach'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppCoursesRouteImport } from './routes/_app/courses'
import { Route as AppDiscussionsRouteImport } from './routes/_app/discussions'
import { Route as AppExamsRouteImport } from './routes/_app/exams'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppMediaRouteImport } from './routes/_app/media'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppRankingsRouteImport } from './routes/_app/rankings'
import { Route as AppSavedRouteImport } from './routes/_app/saved'
import { Route as AppSchoolPayRouteImport } from './routes/_app/school-pay'
import { Route as AppExamsExamIdRouteImport } from './routes/_app/exams.$examId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppCoursesRoute = AppCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscussionsRoute = AppDiscussionsRouteImport.update({
  id: '/discussions',
  path: '/discussions',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsRoute = AppExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingsRoute = AppRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedRoute = AppSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppRoute,
} as any)
const AppSchoolPayRoute = AppSchoolPayRouteImport.update({
  id: '/school-pay',
  path: '/school-pay',
  getParentRoute: () => AppRoute,
} as any)
const AppExamsExamIdRoute = AppExamsExamIdRouteImport.update({
  id: '/$examId',
  path: '/$examId',
  getParentRoute: () => AppExamsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/about': typeof AppAboutRoute
  '/account': typeof AppAccountRoute
  '/admin': typeof AppAdminRoute
  '/coach': typeof AppCoachRoute
  '/contact': typeof AppContactRoute
  '/courses': typeof AppCoursesRoute
  '/discussions': typeof AppDiscussionsRoute
  '/exams': typeof AppExamsRouteWithChildren
  '/library': typeof AppLibraryRoute
  '/media': typeof AppMediaRoute
  '/notifications': typeof AppNotificationsRoute
  '/rankings': typeof AppRankingsRoute
  '/saved': typeof AppSavedRoute
  '/school-pay': typeof AppSchoolPayRoute
  '/exams/$examId': typeof AppExamsExamIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/about': typeof AppAboutRoute
  '/account': typeof AppAccountRoute
  '/admin': typeof AppAdminRoute
  '/coach': typeof AppCoachRoute
  '/contact': typeof AppContactRoute
  '/courses': typeof AppCoursesRoute
  '/discussions': typeof AppDiscussionsRoute
  '/exams': typeof AppExamsRouteWithChildren
  '/library': typeof AppLibraryRoute
  '/media': typeof AppMediaRoute
  '/notifications': typeof AppNotificationsRoute
  '/rankings': typeof AppRankingsRoute
  '/saved': typeof AppSavedRoute
  '/school-pay': typeof AppSchoolPayRoute
  '/': typeof AppIndexRoute
  '/exams/$examId': typeof AppExamsExamIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/about': typeof AppAboutRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/coach': typeof AppCoachRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/courses': typeof AppCoursesRoute
  '/_app/discussions': typeof AppDiscussionsRoute
  '/_app/exams': typeof AppExamsRouteWithChildren
  '/_app/library': typeof AppLibraryRoute
  '/_app/media': typeof AppMediaRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/rankings': typeof AppRankingsRoute
  '/_app/saved': typeof AppSavedRoute
  '/_app/school-pay': typeof AppSchoolPayRoute
  '/_app/': typeof AppIndexRoute
  '/_app/exams/$examId': typeof AppExamsExamIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/about'
    | '/account'
    | '/admin'
    | '/coach'
    | '/contact'
    | '/courses'
    | '/discussions'
    | '/exams'
    | '/library'
    | '/media'
    | '/notifications'
    | '/rankings'
    | '/saved'
    | '/school-pay'
    | '/exams/$examId'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/about'
    | '/account'
    | '/admin'
    | '/coach'
    | '/contact'
    | '/courses'
    | '/discussions'
    | '/exams'
    | '/library'
    | '/media'
    | '/notifications'
    | '/rankings'
    | '/saved'
    | '/school-pay'
    | '/'
    | '/exams/$examId'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/about'
    | '/_app/account'
    | '/_app/admin'
    | '/_app/coach'
    | '/_app/contact'
    | '/_app/courses'
    | '/_app/discussions'
    | '/_app/exams'
    | '/_app/library'
    | '/_app/media'
    | '/_app/notifications'
    | '/_app/rankings'
    | '/_app/saved'
    | '/_app/school-pay'
    | '/_app/'
    | '/_app/exams/$examId'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/courses': {
      id: '/_app/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AppCoursesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discussions': {
      id: '/_app/discussions'
      path: '/discussions'
      fullPath: '/discussions'
      preLoaderRoute: typeof AppDiscussionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exams': {
      id: '/_app/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof AppExamsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/media': {
      id: '/_app/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rankings': {
      id: '/_app/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AppRankingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved': {
      id: '/_app/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AppSavedRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/school-pay': {
      id: '/_app/school-pay'
      path: '/school-pay'
      fullPath: '/school-pay'
      preLoaderRoute: typeof AppSchoolPayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exams/$examId': {
      id: '/_app/exams/$examId'
      path: '/$examId'
      fullPath: '/exams/$examId'
      preLoaderRoute: typeof AppExamsExamIdRouteImport
      parentRoute: typeof AppExamsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppExamsRouteChildren {
  AppExamsExamIdRoute: typeof AppExamsExamIdRoute
}

const AppExamsRouteChildren: AppExamsRouteChildren = {
  AppExamsExamIdRoute: AppExamsExamIdRoute,
}

const AppExamsRouteWithChildren = AppExamsRoute._addFileChildren(
  AppExamsRouteChildren,
)

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAccountRoute: typeof AppAccountRoute
  AppAdminRoute: typeof AppAdminRoute
  AppCoachRoute: typeof AppCoachRoute
  AppContactRoute: typeof AppContactRoute
  AppCoursesRoute: typeof AppCoursesRoute
  AppDiscussionsRoute: typeof AppDiscussionsRoute
  AppExamsRoute: typeof AppExamsRouteWithChildren
  AppLibraryRoute: typeof AppLibraryRoute
  AppMediaRoute: typeof AppMediaRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppRankingsRoute: typeof AppRankingsRoute
  AppSavedRoute: typeof AppSavedRoute
  AppSchoolPayRoute: typeof AppSchoolPayRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAccountRoute: AppAccountRoute,
  AppAdminRoute: AppAdminRoute,
  AppCoachRoute: AppCoachRoute,
  AppContactRoute: AppContactRoute,
  AppCoursesRoute: AppCoursesRoute,
  AppDiscussionsRoute: AppDiscussionsRoute,
  AppExamsRoute: AppExamsRouteWithChildren,
  AppLibraryRoute: AppLibraryRoute,
  AppMediaRoute: AppMediaRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppRankingsRoute: AppRankingsRoute,
  AppSavedRoute: AppSavedRoute,
  AppSchoolPayRoute: AppSchoolPayRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
